### ISSUE TITLE
Out of curiosity, where is exponentiation defined as left multiplication?

### ISSUE THREAD

**Issue by drewstone** [asonnino/coconut-ethereum#1]
I'm seeing this pattern everywhere and trying to wrap my head around a variety of protocols you guys have designed.

https://github.com/musalbas/coconut-ethereum/blob/f953b64351aca8dc45bcc002eb60b4c26f204f0c/ethereum_lib.py#L30

**Comment by asonnino** [comment]
We wrote our prototype based on petlib: http://petlib.readthedocs.io/en/latest/

**Comment by drewstone** [comment]
Isn't this scalar multiplication in petlib though?
<img width="643" alt="screen shot 2018-07-19 at 5 48 42 pm" src="https://user-images.githubusercontent.com/13153687/42954039-01d3eea4-8b7c-11e8-9234-c137c33b4193.png">

I'm also looking to use some of the primitives for Ethereum specific libraries so am using bn128 libraries you guys have included within this repo instead of those based on petlib. Though this is confusing me. What you are saying is that this calculation above is modular exponentiation as well?

EDIT: Here is where I'm stuck.
Lets say I want to sign a message in Pointcheval's scheme:
<img width="509" alt="screen shot 2018-07-19 at 5 59 13 pm" src="https://user-images.githubusercontent.com/13153687/42954648-82fcc31a-8b7d-11e8-8a03-f138b560eea3.png">
```
def sign(params, sk, m):
    (G, o, g1, g2, e) = params
    (x, y) = sk
    r = o.random()
    h = r*g1
    sigma = (h, (x+y*m)*h)
    return sigma
```
How can I compute sigma correctly so that `(x+y*m)` is scalar multiplication and the next operation is exponentiation?
